from pathlib import Path
from typing import Protocol


class FileSystemPort(Protocol):
    def exists(self, path: Path) -> bool: ...

    def mkdir(self, path: Path, parents: bool = False) -> None: ...

    def read_text(self, path: Path) -> str: ...

    def write_text(self, path: Path, content: str) -> None: ...

    def glob(self, root: Path, pattern: str) -> list[Path]: ...
